const DATA_SOURCE = {
    // ============================================================
    // DỮ LIỆU LỚP 10
    // ============================================================
    DaiSo10: [
        { id: "DS10_1", ten: "Chuyên đề 1. Mệnh đề", dang: [ {id: "0D1-1-1", txt: "Xác định mệnh đề"}, {id: "0D1-1-2", txt: "Tính đúng-sai của mệnh đề"}, {id: "0D1-1-3", txt: "Phủ định của một mệnh đề"}, {id: "0D1-1-4", txt: "Mệnh đề kéo theo, đảo, tương đương"}, {id: "0D1-1-5", txt: "Mệnh đề với mọi, tồn tại"}, {id: "0D1-1-6", txt: "Áp dụng mệnh đề vào suy luận"} ] },
        { id: "DS10_2", ten: "Chuyên đề 2. Tập hợp", dang: [ {id: "0D1-2-1", txt: "Tập hợp và phần tử"}, {id: "0D1-2-2", txt: "Tập hợp con. Hai tập hợp bằng nhau"}, {id: "0D1-2-3", txt: "Ký hiệu khoảng, đoạn, nửa khoảng"} ] },
        { id: "DS10_3", ten: "Chuyên đề 3. Phép toán tập hợp", dang: [ {id: "0D1-3-1", txt: "Giao và hợp (rời rạc)"}, {id: "0D1-3-2", txt: "Hiệu và phần bù (rời rạc)"}, {id: "0D1-3-3", txt: "Giao và hợp (đoạn, khoảng)"}, {id: "0D1-3-4", txt: "Hiệu và phần bù (đoạn, khoảng)"}, {id: "0D1-3-5", txt: "Toán thực tế tập hợp"} ] },
        { id: "DS10_4", ten: "Chuyên đề 4. BPT bậc nhất 2 ẩn", dang: [ {id: "0D2-1-1", txt: "Khái niệm BPT bậc nhất hai ẩn"}, {id: "0D2-1-2", txt: "Miền nghiệm BPT bậc nhất hai ẩn"}, {id: "0D2-1-3", txt: "Toán thực tế BPT"} ] },
        { id: "DS10_5", ten: "Chuyên đề 5. Hệ BPT bậc nhất 2 ẩn", dang: [ {id: "0D2-2-1", txt: "Khái niệm Hệ BPT"}, {id: "0D2-2-2", txt: "Miền nghiệm Hệ BPT"}, {id: "0D2-2-3", txt: "Toán thực tế Hệ BPT"} ] },
        { id: "DS10_6", ten: "Chuyên đề 6. Hàm số và đồ thị", dang: [ {id: "0D3-1-1", txt: "Xác định hàm số"}, {id: "0D3-1-2", txt: "Tập xác định"}, {id: "0D3-1-3", txt: "Giá trị hàm số"}, {id: "0D3-1-4", txt: "Đồ thị hàm số"}, {id: "0D3-1-5", txt: "Đồng biến, nghịch biến"}, {id: "0D3-1-6", txt: "Tính chẵn, lẻ"}, {id: "0D3-1-7", txt: "Toán thực tế hàm số"} ] },
        { id: "DS10_7", ten: "Chuyên đề 7. Hàm số bậc hai", dang: [ {id: "0D3-2-1", txt: "Xác định HS bậc hai"}, {id: "0D3-2-2", txt: "Biến thiên, max, min"}, {id: "0D3-2-3", txt: "Đồ thị HS bậc hai"}, {id: "0D3-2-4", txt: "Sự tương giao"}, {id: "0D3-2-5", txt: "HS chứa trị tuyệt đối"}, {id: "0D3-2-6", txt: "Toán thực tế HS bậc hai"} ] },
        { id: "DS10_8", ten: "Chuyên đề 8. Số gần đúng. Sai số", dang: [ {id: "0D6-1-1", txt: "Sai số tuyệt đối, tương đối"}, {id: "0D6-1-2", txt: "Độ chính xác"}, {id: "0D6-1-3", txt: "Quy tròn số"}, {id: "0D6-1-4", txt: "Viết số gần đúng"} ] },
        { id: "DS10_9", ten: "Chuyên đề 9. Mô tả dữ liệu", dang: [ {id: "0D6-2-1", txt: "Phân tích bảng số liệu"}, {id: "0D6-2-2", txt: "Phân tích biểu đồ"}, {id: "0D6-2-3", txt: "Số liệu bất thường (bảng)"}, {id: "0D6-2-4", txt: "Số liệu bất thường (biểu đồ)"} ] },
        { id: "DS10_10", ten: "Chuyên đề 10. Số đặc trưng trung tâm", dang: [ {id: "0D6-3-1", txt: "Lý thuyết"}, {id: "0D6-3-2", txt: "Số trung bình cộng"}, {id: "0D6-3-3", txt: "Số trung vị"}, {id: "0D6-3-4", txt: "Tứ phân vị"}, {id: "0D6-3-5", txt: "Mốt (Mode)"} ] },
        { id: "DS10_11", ten: "Chuyên đề 11. Số đặc trưng phân tán", dang: [ {id: "0D6-4-1", txt: "Lý thuyết"}, {id: "0D6-4-2", txt: "Khoảng biến thiên, tứ phân vị"}, {id: "0D6-4-3", txt: "Giá trị bất thường"}, {id: "0D6-4-4", txt: "Phương sai, độ lệch chuẩn"} ] },
        { id: "DS10_12", ten: "Chuyên đề 12. Dấu tam thức bậc 2", dang: [ {id: "0D7-1-1", txt: "Xác định tam thức"}, {id: "0D7-1-2", txt: "Dấu tam thức & ứng dụng"}, {id: "0D7-1-3", txt: "Xét dấu biết đồ thị"}, {id: "0D7-1-4", txt: "Xét dấu tích, thương"}, {id: "0D7-1-5", txt: "Toán thực tế"} ] },
        { id: "DS10_13", ten: "Chuyên đề 13. Giải BPT bậc 2", dang: [ {id: "0D7-2-1", txt: "Giải BPT bậc 2"}, {id: "0D7-2-2", txt: "Giải BPT biết đồ thị"}, {id: "0D7-2-3", txt: "BPT tích, thương"}, {id: "0D7-2-4", txt: "Hệ BPT bậc 2"}, {id: "0D7-2-5", txt: "BPT chứa căn, trị tuyệt đối"}, {id: "0D7-2-6", txt: "Tham số m"}, {id: "0D7-2-7", txt: "Toán thực tế BPT"} ] },
        { id: "DS10_14", ten: "Chuyên đề 14. PT quy về bậc 2", dang: [ {id: "0D7-3-1", txt: "PT căn f = căn g"}, {id: "0D7-3-2", txt: "PT căn f = g"}, {id: "0D7-3-3", txt: "PT căn có tham số"}, {id: "0D7-3-4", txt: "PT căn dạng khác"}, {id: "0D7-3-5", txt: "PT khác quy về bậc 2"}, {id: "0D7-3-6", txt: "Toán thực tế"} ] },
        { id: "DS10_15", ten: "Chuyên đề 15. Quy tắc cộng - nhân", dang: [ {id: "0D8-1-1", txt: "Quy tắc cộng"}, {id: "0D8-1-2", txt: "Quy tắc nhân"}, {id: "0D8-1-3", txt: "Kết hợp cộng nhân"}, {id: "0D8-1-4", txt: "Quy tắc bù trừ"}, {id: "0D8-1-5", txt: "Đếm số tự nhiên"}, {id: "0D8-1-6", txt: "Sơ đồ cây"} ] },
        { id: "DS10_16", ten: "Chuyên đề 16. Hoán vị - Chỉnh hợp - Tổ hợp", dang: [ {id: "0D8-2-1", txt: "Lý thuyết P, C, A"}, {id: "0D8-2-2", txt: "Biểu thức P, C, A"}, {id: "0D8-2-3", txt: "Đếm số tự nhiên"}, {id: "0D8-2-4", txt: "Chọn người"}, {id: "0D8-2-5", txt: "Chọn đối tượng khác"}, {id: "0D8-2-6", txt: "Yếu tố hình học"}, {id: "0D8-2-7", txt: "Xếp chỗ"}, {id: "0D8-2-8", txt: "Hoán vị bàn tròn"}, {id: "0D8-2-9", txt: "Hoán vị lặp"} ] },
        { id: "DS10_17", ten: "Chuyên đề 17. Nhị thức Newton", dang: [ {id: "0D8-3-1", txt: "Lý thuyết"}, {id: "0D8-3-2", txt: "Khai triển nhị thức"}, {id: "0D8-3-3", txt: "Hệ số (Tam giác Pascal)"}, {id: "0D8-3-4", txt: "Tìm hệ số, số hạng"}, {id: "0D8-3-5", txt: "Tính tổng"}, {id: "0D8-3-6", txt: "Toán tổ hợp dùng Newton"} ] },
        { id: "DS10_18", ten: "Chuyên đề 18. Không gian mẫu", dang: [ {id: "0D10-1-1", txt: "Lý thuyết"}, {id: "0D10-1-2", txt: "Mô tả KGM, biến cố"}, {id: "0D10-1-3", txt: "Đếm phần tử KGM"} ] },
        { id: "DS10_19", ten: "Chuyên đề 19. Xác suất biến cố", dang: [ {id: "0D10-2-1", txt: "Lý thuyết"}, {id: "0D10-2-2", txt: "Xúc xắc, đồng tiền"}, {id: "0D10-2-3", txt: "Sắp xếp chỗ"}, {id: "0D10-2-4", txt: "Chọn người"}, {id: "0D10-2-5", txt: "Chọn vật"}, {id: "0D10-2-6", txt: "Hình học"}, {id: "0D10-2-7", txt: "Đếm số"}, {id: "0D10-2-8", txt: "Bàn tròn, lặp"}, {id: "0D10-2-9", txt: "Vấn đề khác"} ] },
    ],
    HinhHoc10: [
        { id: "HH10_1", ten: "Chuyên đề 1. Giá trị lượng giác (0-180)", dang: [ {id: "0H4-1-1", txt: "Xét dấu"}, {id: "0H4-1-2", txt: "Tính giá trị"}, {id: "0H4-1-3", txt: "Rút gọn biểu thức"} ] },
        { id: "HH10_2", ten: "Chuyên đề 2. Định lý Sin - Cos", dang: [ {id: "0H4-2-1", txt: "Dùng định lý Sin, Cos"}, {id: "0H4-2-2", txt: "Công thức diện tích"}, {id: "0H4-2-3", txt: "Rút gọn biểu thức"}, {id: "0H4-2-4", txt: "Nhận dạng tam giác"} ] },
        { id: "HH10_3", ten: "Chuyên đề 3. Giải tam giác", dang: [ {id: "0H4-3-1", txt: "Giải tam giác"}, {id: "0H4-3-2", txt: "Ứng dụng thực tế"} ] },
        { id: "HH10_4", ten: "Chuyên đề 4. Khái niệm vectơ", dang: [ {id: "0H5-1-1", txt: "Xác định vectơ"}, {id: "0H5-1-2", txt: "Phương và hướng"}, {id: "0H5-1-3", txt: "Vectơ bằng nhau"}, {id: "0H5-1-4", txt: "Vectơ đối nhau"}, {id: "0H5-1-5", txt: "Độ dài vectơ"}, {id: "0H5-1-6", txt: "Toán thực tế"} ] },
        { id: "HH10_5", ten: "Chuyên đề 5. Tổng hiệu vectơ", dang: [ {id: "0H5-2-1", txt: "Thu gọn hiệu vectơ"}, {id: "0H5-2-2", txt: "Đúng sai đẳng thức"}, {id: "0H5-2-3", txt: "Tìm điểm"}, {id: "0H5-2-4", txt: "Độ dài tổng hiệu"}, {id: "0H5-2-5", txt: "Cực trị hình học"}, {id: "0H5-2-6", txt: "Toán thực tế"} ] },
        { id: "HH10_6", ten: "Chuyên đề 6. Tích số với vectơ", dang: [ {id: "0H5-3-1", txt: "Xác định k"}, {id: "0H5-3-2", txt: "Biến đổi đẳng thức"}, {id: "0H5-3-3", txt: "Tìm điểm"}, {id: "0H5-3-4", txt: "Cùng phương"}, {id: "0H5-3-5", txt: "Phân tích vectơ"}, {id: "0H5-3-6", txt: "Độ dài tổng hiệu"}, {id: "0H5-3-7", txt: "Tập hợp điểm"}, {id: "0H5-3-8", txt: "Cực trị"}, {id: "0H5-3-9", txt: "Toán thực tế"} ] },
        { id: "HH10_7", ten: "Chuyên đề 7. Tích vô hướng (thường)", dang: [ {id: "0H5-4-1", txt: "Góc và tích vô hướng"}, {id: "0H5-4-2", txt: "Tìm góc"}, {id: "0H5-4-3", txt: "Đẳng thức"}, {id: "0H5-4-4", txt: "Vuông góc"}, {id: "0H5-4-5", txt: "Tìm điểm, tập hợp điểm"}, {id: "0H5-4-6", txt: "Cực trị, BĐT"}, {id: "0H5-4-7", txt: "Toán thực tế"} ] },
        { id: "HH10_8", ten: "Chuyên đề 8. Tọa độ vectơ", dang: [ {id: "0H9-1-1", txt: "Tọa độ trên trục"}, {id: "0H9-1-2", txt: "Phép toán vectơ Oxy"}, {id: "0H9-1-3", txt: "Tọa độ điểm Oxy"}, {id: "0H9-1-4", txt: "Cùng phương"}, {id: "0H9-1-5", txt: "Phân tích vectơ"}, {id: "0H9-1-6", txt: "Toán thực tế"} ] },
        { id: "HH10_9", ten: "Chuyên đề 9. Tích vô hướng (tọa độ)", dang: [ {id: "0H9-2-1", txt: "Góc và tích vô hướng"}, {id: "0H9-2-2", txt: "Tìm góc"}, {id: "0H9-2-3", txt: "Đẳng thức"}, {id: "0H9-2-4", txt: "Vuông góc"}, {id: "0H9-2-5", txt: "Tìm điểm, tập hợp điểm"}, {id: "0H9-2-6", txt: "Cực trị, BĐT"}, {id: "0H9-2-7", txt: "Toán thực tế"} ] },
        { id: "HH10_10", ten: "Chuyên đề 10. Đường thẳng Oxy", dang: [ {id: "0H9-3-1", txt: "Điểm, VTCP, VTPT, k"}, {id: "0H9-3-2", txt: "PT đường thẳng"}, {id: "0H9-3-3", txt: "Vị trí tương đối"}, {id: "0H9-3-4", txt: "Góc"}, {id: "0H9-3-5", txt: "Khoảng cách"}, {id: "0H9-3-6", txt: "Tìm điểm"}, {id: "0H9-3-7", txt: "Tam giác, tứ giác"}, {id: "0H9-3-8", txt: "Thực tế, tọa độ hóa"} ] },
        { id: "HH10_11", ten: "Chuyên đề 11. Đường tròn Oxy", dang: [ {id: "0H9-4-1", txt: "Tâm, bán kính"}, {id: "0H9-4-2", txt: "PT đường tròn"}, {id: "0H9-4-3", txt: "Tiếp tuyến"}, {id: "0H9-4-4", txt: "Vị trí tương đối"}, {id: "0H9-4-5", txt: "Đường thẳng & Đường tròn"}, {id: "0H9-4-6", txt: "Tam giác, tứ giác"}, {id: "0H9-4-7", txt: "Thực tế"} ] },
        { id: "HH10_12", ten: "Chuyên đề 12. Ba đường Conic", dang: [ {id: "0H9-5-1", txt: "Yếu tố Elip"}, {id: "0H9-5-2", txt: "PT Elip"}, {id: "0H9-5-3", txt: "Điểm trên Elip"}, {id: "0H9-5-4", txt: "Yếu tố Hypebol"}, {id: "0H9-5-5", txt: "PT Hypebol"}, {id: "0H9-5-6", txt: "Điểm trên Hypebol"}, {id: "0H9-5-7", txt: "Yếu tố Parabol"}, {id: "0H9-5-8", txt: "PT Parabol"}, {id: "0H9-5-9", txt: "Điểm trên Parabol"}, {id: "0H9-5-0", txt: "Tổng hợp 3 Conic"} ] }
    ],
    // ============================================================
    // DỮ LIỆU LỚP 11
    // ============================================================
    DaiSo11: [
        { id: "DS11_1", ten: "Chuyên đề 1. Góc lượng giác", dang: [{id: "1D1-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1D1-1-2", txt: "Chuyển đổi đơn vị độ và radian"}, {id: "1D1-1-3", txt: "Số đo của một góc lượng giác"}, {id: "1D1-1-4", txt: "Độ dài của một cung tròn"}, {id: "1D1-1-5", txt: "Đường tròn lượng giác và ứng dụng"}, {id: "1D1-1-6", txt: "Toán thực tế áp dụng góc lượng giác"}] },
        { id: "DS11_2", ten: "Chuyên đề 2. Giá trị lượng giác", dang: [{id: "1D1-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1D1-2-2", txt: "Xét dấu, tính giá trị lượng giác"}, {id: "1D1-2-3", txt: "Biến đổi, rút gọn biểu thức LG"}, {id: "1D1-2-4", txt: "Các góc lượng giác có liên quan đặc biệt"}, {id: "1D1-2-5", txt: "Toán thực tế áp dụng giá trị LG"}] },
        { id: "DS11_3", ten: "Chuyên đề 3. Các công thức lượng giác", dang: [{id: "1D1-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1D1-3-2", txt: "Áp dụng công thức cộng"}, {id: "1D1-3-3", txt: "Áp dụng công thức nhân đôi - hạ bậc"}, {id: "1D1-3-4", txt: "Áp dụng công thức biến đổi tích - tổng"}, {id: "1D1-3-5", txt: "Kết hợp nhiều công thức lượng giác"}, {id: "1D1-3-6", txt: "Nhận dạng tam giác"}, {id: "1D1-3-7", txt: "Toán thực tế áp dụng công thức LG"}] },
        { id: "DS11_4", ten: "Chuyên đề 4. Hàm số lượng giác và đồ thị", dang: [{id: "1D1-4-1", txt: "Câu hỏi lý thuyết"}, {id: "1D1-4-2", txt: "Tìm tập xác định"}, {id: "1D1-4-3", txt: "Xét tính đơn điệu"}, {id: "1D1-4-4", txt: "Xét tính chẵn, lẻ"}, {id: "1D1-4-5", txt: "Xét tính tuần hoàn, tìm chu kỳ"}, {id: "1D1-4-6", txt: "Tìm tập giá trị và min, max"}, {id: "1D1-4-7", txt: "Bảng biến thiên và đồ thị"}, {id: "1D1-4-8", txt: "Toán thực tế áp dụng hàm số LG"}] },
        { id: "DS11_5", ten: "Chuyên đề 5. Phương trình lượng giác cơ bản", dang: [{id: "1D1-5-1", txt: "Lý thuyết, PT tương đương"}, {id: "1D1-5-2", txt: "Điều kiện có nghiệm"}, {id: "1D1-5-3", txt: "Phương trình cơ bản dùng Radian"}, {id: "1D1-5-4", txt: "Phương trình cơ bản dùng Độ"}, {id: "1D1-5-5", txt: "Phương trình đưa về dạng cơ bản"}, {id: "1D1-5-6", txt: "Toán thực tế áp dụng PT LG"}] },
        { id: "DS11_6", ten: "Chuyên đề 6. PT lượng giác thường gặp", dang: [{id: "1D1-6-1", txt: "PT bậc n theo một hàm số LG"}, {id: "1D1-6-2", txt: "PT đẳng cấp bậc n đối với sin, cos"}, {id: "1D1-6-3", txt: "PT bậc nhất đối với sin và cos"}, {id: "1D1-6-4", txt: "PT đối xứng, phản đối xứng"}, {id: "1D1-6-5", txt: "PT lượng giác không mẫu mực"}, {id: "1D1-6-6", txt: "PT LG có chứa ẩn ở mẫu số"}, {id: "1D1-6-7", txt: "PT LG có chứa tham số"}, {id: "1D1-6-8", txt: "Toán thực tế áp dụng PT LG thường gặp"}] },
        { id: "DS11_7", ten: "Chuyên đề 7. Dãy số", dang: [{id: "1D2-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1D2-1-2", txt: "Số hạng tổng quát, biểu diễn dãy số"}, {id: "1D2-1-3", txt: "Tìm số hạng cụ thể của dãy số"}, {id: "1D2-1-4", txt: "Dãy số tăng, dãy số giảm"}, {id: "1D2-1-5", txt: "Dãy số bị chặn"}, {id: "1D2-1-6", txt: "Toán thực tế áp dụng dãy số"}] },
        { id: "DS11_8", ten: "Chuyên đề 8. Cấp số cộng", dang: [{id: "1D2-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1D2-2-2", txt: "Nhận diện CSC, công sai d"}, {id: "1D2-2-3", txt: "Số hạng tổng quát của CSC"}, {id: "1D2-2-4", txt: "Tìm số hạng cụ thể trong CSC"}, {id: "1D2-2-5", txt: "Điều kiện để dãy số là CSC"}, {id: "1D2-2-6", txt: "Tính tổng của cấp số cộng"}, {id: "1D2-2-7", txt: "Toán thực tế áp dụng CSC"}] },
        { id: "DS11_9", ten: "Chuyên đề 9. Cấp số nhân", dang: [{id: "1D2-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1D2-3-2", txt: "Nhận diện CSN, công bội q"}, {id: "1D2-3-3", txt: "Số hạng tổng quát của CSN"}, {id: "1D2-3-4", txt: "Tìm số hạng cụ thể trong CSN"}, {id: "1D2-3-5", txt: "Điều kiện để dãy số là CSN"}, {id: "1D2-3-6", txt: "Tính tổng của CSN"}, {id: "1D2-3-7", txt: "Kết hợp cấp số nhân và cấp số cộng"}, {id: "1D2-3-8", txt: "Toán thực tế áp dụng CSN"}] },
        { id: "DS11_10", ten: "Chuyên đề 10. Giới hạn của dãy số", dang: [{id: "1D3-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1D3-1-2", txt: "PP đặt thừa số chung (lim hữu hạn)"}, {id: "1D3-1-3", txt: "PP lượng liên hợp (lim hữu hạn)"}, {id: "1D3-1-4", txt: "Giới hạn vô cực"}, {id: "1D3-1-5", txt: "Cấp số nhân lùi vô hạn"}, {id: "1D3-1-6", txt: "Toán thực tế áp dụng giới hạn dãy số"}] },
        { id: "DS11_11", ten: "Chuyên đề 11. Giới hạn của hàm số", dang: [{id: "1D3-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1D3-2-2", txt: "Thay số trực tiếp"}, {id: "1D3-2-3", txt: "PP đặt thừa số chung, hữu hạn"}, {id: "1D3-2-4", txt: "PP đặt thừa số chung, vô cực"}, {id: "1D3-2-5", txt: "PP lượng liên hợp, hữu hạn"}, {id: "1D3-2-6", txt: "PP lượng liên hợp, vô cực"}, {id: "1D3-2-7", txt: "Giới hạn một bên"}, {id: "1D3-2-8", txt: "Toán thực tế áp dụng GH hàm số"}] },
        { id: "DS11_12", ten: "Chuyên đề 12. Hàm số liên tục", dang: [{id: "1D3-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1D3-3-2", txt: "Tính liên tục qua đồ thị"}, {id: "1D3-3-3", txt: "Hàm số liên tục tại một điểm"}, {id: "1D3-3-4", txt: "Hàm số liên tục trên khoảng/đoạn"}, {id: "1D3-3-5", txt: "Bài toán phương trình có nghiệm"}, {id: "1D3-3-6", txt: "Toán thực tế áp dụng HS liên tục"}] },
        { id: "DS11_13", ten: "Chuyên đề 13. Số trung bình và mốt (ghép nhóm)", dang: [{id: "1D5-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1D5-1-2", txt: "Mẫu số liệu ghép nhóm"}, {id: "1D5-1-3", txt: "Số trung bình"}, {id: "1D5-1-4", txt: "Mốt"}] },
        { id: "DS11_14", ten: "Chuyên đề 14. Trung vị và tứ phân vị (ghép nhóm)", dang: [{id: "1D5-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1D5-2-2", txt: "Trung vị"}, {id: "1D5-2-3", txt: "Tứ phân vị"}] },
        { id: "DS11_15", ten: "Chuyên đề 15. Phép tính lũy thừa", dang: [{id: "1D6-1-1", txt: "Tính giá trị biểu thức lũy thừa"}, {id: "1D6-1-2", txt: "Biến đổi, rút gọn biểu thức"}, {id: "1D6-1-3", txt: "Điều kiện cho lũy thừa, căn thức"}, {id: "1D6-1-4", txt: "So sánh các lũy thừa"}] },
        { id: "DS11_16", ten: "Chuyên đề 16. Phép tính lôgarit", dang: [{id: "1D6-2-1", txt: "Tính giá trị biểu thức lôgarit"}, {id: "1D6-2-2", txt: "Biến đổi, biểu diễn biểu thức"}, {id: "1D6-2-3", txt: "Rút gọn, chứng minh đẳng thức"}, {id: "1D6-2-4", txt: "Số e và bài toán lãi kép"}, {id: "1D6-2-5", txt: "Toán thực tế áp dụng lôgarit"}] },
        { id: "DS11_17", ten: "Chuyên đề 17. Hàm số mũ. Hàm số lôgarit", dang: [{id: "1D6-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1D6-3-2", txt: "Tập xác định của hàm số"}, {id: "1D6-3-3", txt: "Sự biến thiên và đồ thị"}, {id: "1D6-3-4", txt: "So sánh các lũy thừa và lôgarit"}, {id: "1D6-3-5", txt: "Toán thực tế áp dụng hàm mũ, log"}] },
        { id: "DS11_18", ten: "Chuyên đề 18. PT, BPT mũ và lôgarit", dang: [{id: "1D6-4-1", txt: "Điều kiện có nghiệm"}, {id: "1D6-4-2", txt: "Phương trình mũ, lôgarit cơ bản"}, {id: "1D6-4-3", txt: "Bất phương trình mũ, log cơ bản"}, {id: "1D6-4-4", txt: "PT mũ, log đưa về cùng cơ số"}, {id: "1D6-4-5", txt: "BPT mũ, log đưa về cùng cơ số"}, {id: "1D6-4-6", txt: "Toán thực tế áp dụng PT mũ, log"}] },
        { id: "DS11_19", ten: "Chuyên đề 19. Các PP giải được giảm tải", dang: [{id: "1D6-5-1", txt: "PP đặt ẩn phụ cho PT mũ, log"}, {id: "1D6-5-2", txt: "PP logarit hóa, mũ hóa"}, {id: "1D6-5-3", txt: "PP hàm số, đánh giá"}, {id: "1D6-5-4", txt: "Hệ PT mũ, lôgarit"}, {id: "1D6-5-5", txt: "Toán thực tế áp dụng PT mũ, log"}] },
        { id: "DS11_20", ten: "Chuyên đề 20. Đạo hàm", dang: [{id: "1D7-1-1", txt: "Tính đạo hàm bằng định nghĩa"}, {id: "1D7-1-2", txt: "Số gia hàm số, số gia biến số"}, {id: "1D7-1-3", txt: "Ý nghĩa Hình học của đạo hàm"}, {id: "1D7-1-4", txt: "Ý nghĩa Vật lý của đạo hàm"}, {id: "1D7-1-5", txt: "Toán thực tế áp dụng định nghĩa"}] },
        { id: "DS11_21", ten: "Chuyên đề 21. Các quy tắc đạo hàm", dang: [{id: "1D7-2-1", txt: "Tính đạo hàm"}, {id: "1D7-2-2", txt: "Đẳng thức có y và y'"}, {id: "1D7-2-3", txt: "Tiếp tuyến tại một điểm"}, {id: "1D7-2-4", txt: "Tiếp tuyến biết trước hệ số góc"}, {id: "1D7-2-5", txt: "Tiếp tuyến chưa biết tiếp điểm"}, {id: "1D7-2-6", txt: "Giới hạn hàm lượng giác, mũ, log"}, {id: "1D7-2-7", txt: "Dùng đạo hàm cho nhị thức Newton"}, {id: "1D7-2-8", txt: "Toán thực tế áp dụng quy tắc đạo hàm"}] },
        { id: "DS11_22", ten: "Chuyên đề 22. Đạo hàm cấp hai", dang: [{id: "1D7-3-1", txt: "Tính đạo hàm cấp hai"}, {id: "1D7-3-2", txt: "Đẳng thức có y và (y', y'')"}, {id: "1D7-3-3", txt: "Toán thực tế và Vật lý đạo hàm cấp 2"}] },
    ],
    HinhHoc11: [
        { id: "HH11_1", ten: "Chuyên đề 1. Phép biến hình, phép dời hình", dang: [{id: "1C1-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-1-2", txt: "Xác định phép dời hình"}, {id: "1C1-1-3", txt: "Xác định ảnh qua phép dời hình"}] },
        { id: "HH11_2", ten: "Chuyên đề 2. Phép tịnh tiến", dang: [{id: "1C1-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-2-2", txt: "Tìm ảnh/tạo ảnh qua phép tịnh tiến"}, {id: "1C1-2-3", txt: "Ứng dụng phép tịnh tiến"}] },
        { id: "HH11_3", ten: "Chuyên đề 3. Phép đối xứng trục", dang: [{id: "1C1-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-3-2", txt: "Tìm ảnh/tạo ảnh qua ĐX trục"}, {id: "1C1-3-3", txt: "Xác định trục đối xứng"}, {id: "1C1-3-4", txt: "Ứng dụng phép đối xứng trục"}] },
        { id: "HH11_4", ten: "Chuyên đề 4. Phép đối xứng tâm", dang: [{id: "1C1-4-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-4-2", txt: "Tìm ảnh/tạo ảnh qua ĐX tâm"}, {id: "1C1-4-3", txt: "Xác định tâm đối xứng"}, {id: "1C1-4-4", txt: "Ứng dụng phép đối xứng tâm"}] },
        { id: "HH11_5", ten: "Chuyên đề 5. Phép quay", dang: [{id: "1C1-5-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-5-2", txt: "Xác định vị trí ảnh của điểm, hình"}, {id: "1C1-5-3", txt: "Tìm tọa độ ảnh, phương trình đường thẳng"}, {id: "1C1-5-4", txt: "Ứng dụng phép quay"}] },
        { id: "HH11_6", ten: "Chuyên đề 6. Phép vị tự", dang: [{id: "1C1-6-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-6-2", txt: "Xác định ảnh, tạo ảnh qua vị tự"}, {id: "1C1-6-3", txt: "Tìm tâm vị tự của hai đường tròn"}, {id: "1C1-6-4", txt: "Ứng dụng phép vị tự"}] },
        { id: "HH11_7", ten: "Chuyên đề 7. Phép đồng dạng", dang: [{id: "1C1-7-1", txt: "Câu hỏi lý thuyết"}, {id: "1C1-7-2", txt: "Xác định ảnh, tạo ảnh qua đồng dạng"}] },
        { id: "HH11_8", ten: "Chuyên đề 8. Đồ thị (Lý thuyết đồ thị)", dang: [{id: "1C2-1-1", txt: "Câu hỏi về đỉnh, cạnh của đồ thị"}, {id: "1C2-1-2", txt: "Câu hỏi về bậc của đồ thị"}, {id: "1C2-1-3", txt: "Câu hỏi tổng hợp"}] },
        { id: "HH11_9", ten: "Chuyên đề 9. Đường đi Euler và Hamilton", dang: [{id: "1C2-2-1", txt: "Đường đi Euler"}, {id: "1C2-2-2", txt: "Đường đi Hamilton"}, {id: "1C2-2-3", txt: "Câu hỏi tổng hợp"}] },
        { id: "HH11_10", ten: "Chuyên đề 10. Bài toán tìm đường đi ngắn nhất", dang: [{id: "1C2-3-1", txt: "Bài toán tìm đường đi ngắn nhất"}, {id: "1C2-3-2", txt: "Tổng hợp"}] },
        { id: "HH11_11", ten: "Chuyên đề 11. Hình biểu diễn của một hình, khối", dang: [{id: "1C3-1-1", txt: "Lý thuyết phép chiếu song song"}, {id: "1C3-1-2", txt: "Lý thuyết phép chiếu vuông góc"}, {id: "1C3-1-3", txt: "Lý thuyết phép chiếu trục đo"}, {id: "1C3-1-4", txt: "Tổng hợp"}] },
        { id: "HH11_12", ten: "Chuyên đề 12. Bản vẽ kỹ thuật", dang: [{id: "1C3-2-1", txt: "Lý thuyết cơ bản bản vẽ kỹ thuật"}, {id: "1C3-2-2", txt: "Phương pháp biểu diễn bản vẽ"}, {id: "1C3-2-3", txt: "Tổng hợp"}] },
        { id: "HH11_13", ten: "Chuyên đề 13. Điểm, đường thẳng và mặt phẳng", dang: [{id: "1H4-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-1-2", txt: "Hình biểu diễn của hình không gian"}, {id: "1H4-1-3", txt: "Tìm giao tuyến của hai mặt phẳng"}, {id: "1H4-1-4", txt: "Tìm giao điểm đường thẳng và mặt phẳng"}, {id: "1H4-1-5", txt: "Xác định thiết diện"}, {id: "1H4-1-6", txt: "Ba điểm thẳng hàng, ba đường đồng quy"}, {id: "1H4-1-7", txt: "Toán thực tế áp dụng điểm, đường, mặt"}] },
        { id: "HH11_14", ten: "Chuyên đề 14. Hai đường thẳng song song", dang: [{id: "1H4-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-2-2", txt: "Hai đường thẳng song song"}, {id: "1H4-2-3", txt: "Tìm giao tuyến bằng cách kẻ song song"}, {id: "1H4-2-4", txt: "Tìm giao điểm của đường và mặt"}, {id: "1H4-2-5", txt: "Xác định thiết diện (kẻ song song)"}, {id: "1H4-2-6", txt: "Ba điểm thẳng hàng"}, {id: "1H4-2-7", txt: "Bài toán quỹ tích và điểm cố định"}, {id: "1H4-2-8", txt: "Toán thực tế áp dụng hai đường song song"}] },
        { id: "HH11_15", ten: "Chuyên đề 15. Đường thẳng và mặt phẳng song song", dang: [{id: "1H4-3-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-3-2", txt: "Đường thẳng song song với mặt phẳng"}, {id: "1H4-3-3", txt: "Tìm giao tuyến bằng cách kẻ song song"}, {id: "1H4-3-4", txt: "Tìm giao điểm đường và mặt"}, {id: "1H4-3-5", txt: "Xác định thiết diện (kẻ song song)"}, {id: "1H4-3-6", txt: "Ba điểm thẳng hàng"}, {id: "1H4-3-7", txt: "Bài toán quỹ tích và điểm cố định"}, {id: "1H4-3-8", txt: "Toán thực tế đường song song mặt"}] },
        { id: "HH11_16", ten: "Chuyên đề 16. Hai mặt phẳng song song", dang: [{id: "1H4-4-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-4-2", txt: "Hai mặt phẳng song song"}, {id: "1H4-4-3", txt: "Chứng minh đường song song mặt"}, {id: "1H4-4-4", txt: "Xác định MP qua 1 điểm song song 1 MP"}, {id: "1H4-4-5", txt: "Xác định MP chứa đường song song MP"}, {id: "1H4-4-6", txt: "Bài toán tổng hợp"}, {id: "1H4-4-7", txt: "Toán thực tế hai mặt phẳng song song"}] },
        { id: "HH11_17", ten: "Chuyên đề 17. Hình lăng trụ và hình hộp (xiên)", dang: [{id: "1H4-5-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-5-2", txt: "Bài toán về hình lăng trụ (xiên)"}, {id: "1H4-5-3", txt: "Bài toán về hình hộp (xiên)"}, {id: "1H4-5-4", txt: "Toán thực tế áp dụng lăng trụ, hình hộp"}] },
        { id: "HH11_18", ten: "Chuyên đề 18. Phép chiếu song song", dang: [{id: "1H4-6-1", txt: "Câu hỏi lý thuyết"}, {id: "1H4-6-2", txt: "Hình biểu diễn của một hình không gian"}, {id: "1H4-6-3", txt: "Xác định yếu tố song song"}, {id: "1H4-6-4", txt: "Xác định phương chiếu"}, {id: "1H4-6-5", txt: "Tính tỉ số đoạn thẳng, diện tích"}] },
        { id: "HH11_19", ten: "Chuyên đề 19. Hai đường thẳng vuông góc", dang: [{id: "1H8-1-1", txt: "Câu hỏi lý thuyết"}, {id: "1H8-1-2", txt: "Xác định hai đường thẳng vuông góc"}, {id: "1H8-1-3", txt: "Tìm góc giữa hai đường thẳng"}, {id: "1H8-1-4", txt: "Toán thực tế hai đường thẳng vuông góc"}] },
        { id: "HH11_20", ten: "Chuyên đề 20. Đường thẳng vuông góc với mặt phẳng", dang: [{id: "1H8-2-1", txt: "Câu hỏi lý thuyết"}, {id: "1H8-2-2", txt: "CM đường thẳng vuông góc mặt phẳng"}, {id: "1H8-2-3", txt: "CM hai đường thẳng vuông góc"}, {id: "1H8-2-4", txt: "Dựng mặt phẳng, tìm thiết diện"}, {id: "1H8-2-5", txt: "Hình chiếu vuông góc của một hình"}, {id: "1H8-2-6", txt: "Toán thực tế đường vuông góc mặt"}] },
        { id: "HH11_21", ten: "Chuyên đề 21. Phép chiếu vuông góc", dang: [{id: "1H8-3-1", txt: "Lý thuyết phép chiếu vuông góc"}, {id: "1H8-3-2", txt: "Hình chiếu vuông góc đa giác trên MP"}, {id: "1H8-3-3", txt: "Toán thực tế áp dụng phép chiếu VG"}] },
        { id: "HH11_22", ten: "Chuyên đề 22. Hai mặt phẳng vuông góc", dang: [{id: "1H8-4-1", txt: "Câu hỏi lý thuyết"}, {id: "1H8-4-2", txt: "CM đường vuông góc mặt, mặt VG mặt"}, {id: "1H8-4-3", txt: "Xác định góc giữa hai mặt phẳng"}, {id: "1H8-4-4", txt: "Dựng mặt phẳng, thiết diện"}, {id: "1H8-4-5", txt: "Nhận dạng và tính toán hình thông dụng"}, {id: "1H8-4-6", txt: "Bài toán cho trước góc giữa d và (P)"}, {id: "1H8-4-7", txt: "Toán thực tế hai mặt phẳng vuông góc"}] },
        { id: "HH11_23", ten: "Chuyên đề 23. Khoảng cách", dang: [{id: "1H8-5-1", txt: "Câu hỏi lý thuyết"}, {id: "1H8-5-2", txt: "KC giữa 2 điểm, điểm đến đường thẳng"}, {id: "1H8-5-3", txt: "KC từ một điểm đến một mặt phẳng"}, {id: "1H8-5-4", txt: "KC giữa hai đường thẳng chéo nhau"}, {id: "1H8-5-5", txt: "Đường vuông góc chung"}, {id: "1H8-5-6", txt: "Toán thực tế áp dụng khoảng cách"}] },
        { id: "HH11_24", ten: "Chuyên đề 24. Góc giữa đường và mặt. Góc nhị diện", dang: [{id: "1H8-6-1", txt: "Góc giữa đường thẳng và mặt phẳng"}, {id: "1H8-6-2", txt: "Góc nhị diện, góc phẳng nhị diện"}, {id: "1H8-6-3", txt: "Góc giữa 2 MP, biết trước góc (d,P)"}, {id: "1H8-6-4", txt: "KC giữa điểm, đường, biết góc (d,P)"}, {id: "1H8-6-5", txt: "KC giữa điểm - mặt, biết góc (d,P)"}, {id: "1H8-6-6", txt: "KC giữa 2 đường chéo nhau, biết góc"}, {id: "1H8-6-7", txt: "Thực tế về góc đường, mặt, nhị diện"}] },
        { id: "HH11_25", ten: "Chuyên đề 25. Hình lăng trụ đứng. Hình chóp đều", dang: [{id: "1H8-7-1", txt: "Lý thuyết, công thức thể tích"}, {id: "1H8-7-2", txt: "Thể tích khối chóp tam giác"}, {id: "1H8-7-3", txt: "Thể tích khối chóp tứ giác"}, {id: "1H8-7-4", txt: "Thể tích khối lăng trụ tam giác"}, {id: "1H8-7-5", txt: "Thể tích khối lăng trụ tứ giác"}, {id: "1H8-7-6", txt: "Thể tích khối chóp cụt và khối khác"}, {id: "1H8-7-7", txt: "Tỉ số thể tích"}, {id: "1H8-7-8", txt: "Ứng dụng thể tích tính góc, khoảng cách"}, {id: "1H8-7-9", txt: "Toán thực tế lăng trụ đứng, chóp đều"}] }
    ],
    // ============================================================
    // DỮ LIỆU LỚP 12
    // ============================================================
    DaiSo12: [
        { id: "12D_1", ten: "Chuyên đề 1. Sự đồng biến và nghịch biến", dang: [ {id: "2D1-1-1", txt: "Xét tính đơn điệu cho bởi công thức"}, {id: "2D1-1-2", txt: "Xét tính đơn điệu dựa vào BBT, đồ thị"}, {id: "2D1-1-3", txt: "Tìm tham số m để hàm số đơn điệu"}, {id: "2D1-1-4", txt: "Ứng dụng tính đơn điệu chứng minh BĐT, PT"}, {id: "2D1-1-5", txt: "Toán thực tế ứng dụng"} ] },
        { id: "12D_2", ten: "Chuyên đề 2. Cực trị của hàm số", dang: [ {id: "2D1-2-1", txt: "Tìm cực trị của hàm số cho bởi công thức"}, {id: "2D1-2-2", txt: "Tìm cực trị dựa vào BBT, đồ thị"}, {id: "2D1-2-3", txt: "Tìm m để hàm số đạt cực trị tại x0"}, {id: "2D1-2-4", txt: "Tìm m để HS bậc 3 có cực trị thỏa mãn ĐK"}, {id: "2D1-2-5", txt: "Tìm m để HS trùng phương có cực trị thỏa ĐK"}, {id: "2D1-2-6", txt: "Tìm m để các hàm số khác có cực trị thỏa ĐK"}, {id: "2D1-2-7", txt: "Toán thực tế ứng dụng"} ] },
        { id: "12D_3", ten: "Chuyên đề 3. GTLN và GTNN", dang: [ {id: "2D1-3-1", txt: "GTLN, GTNN trên đoạn [a;b]"}, {id: "2D1-3-2", txt: "GTLN, GTNN trên khoảng"}, {id: "2D1-3-3", txt: "Sử dụng đánh giá, BĐT cổ điển"}, {id: "2D1-3-4", txt: "Ứng dụng GTLN, GTNN trong bài toán PT, BPT"}, {id: "2D1-3-5", txt: "GTLN, GTNN hàm nhiều biến"}, {id: "2D1-3-6", txt: "Toán thực tế ứng dụng"} ] },
        { id: "12D_4", ten: "Chuyên đề 4. Đường tiệm cận", dang: [ {id: "2D1-4-1", txt: "Tìm tiệm cận (không tham số) hoặc biết BBT"}, {id: "2D1-4-2", txt: "Tìm tiệm cận của hàm số có chứa tham số"}, {id: "2D1-4-3", txt: "Bài toán liên quan đồ thị và tiệm cận"}, {id: "2D1-4-4", txt: "Toán thực tế ứng dụng"} ] },
        { id: "12D_5", ten: "Chuyên đề 5. Khảo sát biến thiên và đồ thị", dang: [ {id: "2D1-5-1", txt: "Nhận dạng đồ thị"}, {id: "2D1-5-2", txt: "Các phép biến đổi đồ thị"}, {id: "2D1-5-3", txt: "Biện luận số giao điểm dựa vào đồ thị, BBT"}, {id: "2D1-5-4", txt: "Sự tương giao của hai đồ thị (tọa độ giao điểm)"}, {id: "2D1-5-5", txt: "Đồ thị của hàm đạo hàm"}, {id: "2D1-5-6", txt: "Phương trình tiếp tuyến của đồ thị hàm số"}, {id: "2D1-5-7", txt: "Điểm đặc biệt của đồ thị hàm số"}, {id: "2D1-5-8", txt: "Toán thực tế ứng dụng"} ] },
        { id: "12D_6", ten: "Chuyên đề 6. Khoảng biến thiên, tứ phân vị (ghép nhóm)", dang: [ {id: "2D3-1-1", txt: "Công thức lý thuyết"}, {id: "2D3-1-2", txt: "Tìm khoảng biến thiên"}, {id: "2D3-1-3", txt: "Tìm khoảng tứ phân vị"}, {id: "2D3-1-4", txt: "Câu hỏi tổng hợp"} ] },
        { id: "12D_7", ten: "Chuyên đề 7. Phương sai, độ lệch chuẩn (ghép nhóm)", dang: [ {id: "2D3-2-1", txt: "Công thức lý thuyết"}, {id: "2D3-2-2", txt: "Tìm phương sai, độ lệch chuẩn"}, {id: "2D3-2-3", txt: "Câu hỏi tổng hợp"} ] },
        { id: "12D_8", ten: "Chuyên đề 8. Nguyên hàm", dang: [ {id: "2D4-1-1", txt: "Công thức lý thuyết"}, {id: "2D4-1-2", txt: "Nguyên hàm cơ bản đa thức, phân thức"}, {id: "2D4-1-3", txt: "Nguyên hàm cơ bản hàm lượng giác"}, {id: "2D4-1-4", txt: "Nguyên hàm cơ bản hàm mũ, lũy thừa"}, {id: "2D4-1-5", txt: "Phương pháp đổi biến số cơ bản"}, {id: "2D4-1-6", txt: "Toán thực tế áp dụng"} ] },
        { id: "12D_9", ten: "Chuyên đề 9. Tích phân", dang: [ {id: "2D4-2-1", txt: "Công thức lý thuyết"}, {id: "2D4-2-2", txt: "Tích phân cơ bản đa thức, phân thức"}, {id: "2D4-2-3", txt: "Tích phân cơ bản hàm lượng giác"}, {id: "2D4-2-4", txt: "Tích phân cơ bản hàm mũ, lũy thừa"}, {id: "2D4-2-5", txt: "Phương pháp đổi biến số cơ bản"}, {id: "2D4-2-6", txt: "Toán thực tế áp dụng"} ] },
        { id: "12D_10", ten: "Chuyên đề 10. Ứng dụng tích phân", dang: [ {id: "2D4-3-1", txt: "Diện tích hình phẳng giới hạn bởi các đồ thị"}, {id: "2D4-3-2", txt: "Bài toán thực tế diện tích hình phẳng"}, {id: "2D4-3-3", txt: "Thể tích giới hạn bởi các đồ thị (tròn xoay)"}, {id: "2D4-3-4", txt: "Thể tích tính theo mặt cắt S(x)"}, {id: "2D4-3-5", txt: "Bài toán thực tế thể tích tròn xoay"} ] },
        { id: "12D_11", ten: "Chuyên đề 11. Xác suất có điều kiện", dang: [ {id: "2D6-1-1", txt: "Công thức lý thuyết"}, {id: "2D6-1-2", txt: "Tính XS có điều kiện bằng công thức"}, {id: "2D6-1-3", txt: "Tính XS có điều kiện bằng sơ đồ cây"}, {id: "2D6-1-4", txt: "Bài toán tổng hợp"} ] },
        { id: "12D_12", ten: "Chuyên đề 12. Xác suất toàn phần - Bayes", dang: [ {id: "2D6-2-1", txt: "Công thức lý thuyết"}, {id: "2D6-2-2", txt: "Tính xác suất bằng công thức XS toàn phần"}, {id: "2D6-2-3", txt: "Tính xác suất bằng công thức XS Bayes"}, {id: "2D6-2-4", txt: "Bài toán tổng hợp"} ] },
    ],
    HinhHoc12: [
        { id: "12H_1", ten: "Chuyên đề 1. Vectơ trong không gian", dang: [ {id: "2H2-1-1", txt: "Công thức lý thuyết"}, {id: "2H2-1-2", txt: "Tổng, hiệu, tích một số với vectơ"}, {id: "2H2-1-3", txt: "Tích vô hướng và ứng dụng"}, {id: "2H2-1-4", txt: "Toán thực tế áp dụng"} ] },
        { id: "12H_2", ten: "Chuyên đề 2. Tọa độ của vectơ và các công thức", dang: [ {id: "2H2-2-1", txt: "Công thức lý thuyết"}, {id: "2H2-2-2", txt: "Tìm tọa độ điểm"}, {id: "2H2-2-3", txt: "Tìm tọa độ vectơ"}, {id: "2H2-2-4", txt: "Công thức tọa độ của tích vô hướng"}, {id: "2H2-2-5", txt: "Công thức tọa độ của tích có hướng"}, {id: "2H2-2-6", txt: "Toán thực tế áp dụng"} ] },
        { id: "12H_3", ten: "Chuyên đề 3. Phương trình mặt phẳng", dang: [ {id: "2H5-1-1", txt: "Câu hỏi lý thuyết"}, {id: "2H5-1-2", txt: "Xác định VTPT, cặp VTCP"}, {id: "2H5-1-3", txt: "Viết phương trình tổng quát mặt phẳng"}, {id: "2H5-1-4", txt: "Vị trí tương đối giữa hai mặt phẳng"}, {id: "2H5-1-5", txt: "Khoảng cách điểm tới mặt phẳng"}, {id: "2H5-1-6", txt: "Góc giữa hai mặt phẳng"}, {id: "2H5-1-7", txt: "Toán thực tế áp dụng"} ] },
        { id: "12H_4", ten: "Chuyên đề 4. Phương trình đường thẳng", dang: [ {id: "2H5-2-1", txt: "Câu hỏi lý thuyết"}, {id: "2H5-2-2", txt: "Xác định VTCP, cặp VTPT"}, {id: "2H5-2-3", txt: "Viết PT tổng quát, chính tắc, tham số"}, {id: "2H5-2-4", txt: "Vị trí tương đối giữa hai đường thẳng"}, {id: "2H5-2-5", txt: "Vị trí tương đối giữa đường thẳng và mặt phẳng"}, {id: "2H5-2-6", txt: "Khoảng cách điểm tới đường thẳng"}, {id: "2H5-2-7", txt: "Góc giữa hai đường, đường và mặt"}, {id: "2H5-2-8", txt: "Toán thực tế áp dụng"} ] },
        { id: "12H_5", ten: "Chuyên đề 5. Phương trình mặt cầu", dang: [ {id: "2H5-3-1", txt: "Câu hỏi lý thuyết"}, {id: "2H5-3-2", txt: "Xác định tâm, bán kính, đường kính"}, {id: "2H5-3-3", txt: "Viết phương trình tổng quát mặt cầu"}, {id: "2H5-3-4", txt: "Toán thực tế áp dụng"} ] }
    ],
    // ============================================================
    // DỮ LIỆU SAT
    // ============================================================
    SAT_Data: [
        // Algebra
        { id: "SAT_A1", ten: "Linear equations in one variable", dang: [{id: "S-A1-1", txt: "Solving linear equations"}, {id: "S-A1-2", txt: "Interpreting constants/variables"}, {id: "S-A1-3", txt: "Word problems"}] },
        { id: "SAT_A2", ten: "Linear functions", dang: [{id: "S-A2-1", txt: "Function notation & evaluation"}, {id: "S-A2-2", txt: "Graphs of linear functions"}, {id: "S-A2-3", txt: "Linear modeling"}] },
        { id: "SAT_A3", ten: "Linear equations in two variables", dang: [{id: "S-A3-1", txt: "Standard & Slope-intercept forms"}, {id: "S-A3-2", txt: "Graphing lines"}, {id: "S-A3-3", txt: "Real-world context"}] },
        { id: "SAT_A4", ten: "Systems of two linear equations", dang: [{id: "S-A4-1", txt: "Solving by substitution/elimination"}, {id: "S-A4-2", txt: "No solution / Infinitely many"}, {id: "S-A4-3", txt: "Systems word problems"}] },
        { id: "SAT_A5", ten: "Linear inequalities", dang: [{id: "S-A5-1", txt: "Solving inequalities (1 variable)"}, {id: "S-A5-2", txt: "Graphing inequalities (2 variables)"}, {id: "S-A5-3", txt: "Systems of inequalities"}] },
        
        // Problem Solving
        { id: "SAT_P1", ten: "Ratios, rates, proportional relationships", dang: [{id: "S-P1-1", txt: "Calculating ratios & rates"}, {id: "S-P1-2", txt: "Unit conversion"}, {id: "S-P1-3", txt: "Proportional word problems"}] },
        { id: "SAT_P2", ten: "Percentages", dang: [{id: "S-P2-1", txt: "Percent change (increase/decrease)"}, {id: "S-P2-2", txt: "Simple & Compound interest"}, {id: "S-P2-3", txt: "Percent of a number"}] },
        { id: "SAT_P3", ten: "One-variable data (Center & Spread)", dang: [{id: "S-P3-1", txt: "Mean, Median, Mode"}, {id: "S-P3-2", txt: "Range & Standard Deviation"}, {id: "S-P3-3", txt: "Box plots & Histograms"}] },
        { id: "SAT_P4", ten: "Two-variable data (Scatterplots)", dang: [{id: "S-P4-1", txt: "Line of best fit"}, {id: "S-P4-2", txt: "Interpreting slope/intercept"}, {id: "S-P4-3", txt: "Making predictions"}] },
        { id: "SAT_P5", ten: "Probability", dang: [{id: "S-P5-1", txt: "Simple probability"}, {id: "S-P5-2", txt: "Conditional probability"}, {id: "S-P5-3", txt: "Probability from tables"}] },
        { id: "SAT_P6", ten: "Inference & Sample statistics", dang: [{id: "S-P6-1", txt: "Sample vs Population"}, {id: "S-P6-2", txt: "Margin of error"}, {id: "S-P6-3", txt: "Confidence intervals"}] },
        { id: "SAT_P7", ten: "Evaluating statistical claims", dang: [{id: "S-P7-1", txt: "Observational studies vs Experiments"}, {id: "S-P7-2", txt: "Bias & Sampling methods"}] },

        // Advanced Math
        { id: "SAT_M1", ten: "Nonlinear functions", dang: [{id: "S-M1-1", txt: "Quadratic functions"}, {id: "S-M1-2", txt: "Exponential functions"}, {id: "S-M1-3", txt: "Graphs of nonlinear functions"}] },
        { id: "SAT_M2", ten: "Nonlinear equations & Systems", dang: [{id: "S-M2-1", txt: "Solving quadratic equations"}, {id: "S-M2-2", txt: "Radical & Rational equations"}, {id: "S-M2-3", txt: "Linear-Quadratic Systems"}] },
        { id: "SAT_M3", ten: "Equivalent expressions", dang: [{id: "S-M3-1", txt: "Polynomial operations"}, {id: "S-M3-2", txt: "Rational expressions"}, {id: "S-M3-3", txt: "Exponents & Radicals structure"}] },

        // Geometry
        { id: "SAT_G1", ten: "Area and volume", dang: [{id: "S-G1-1", txt: "Area of 2D shapes"}, {id: "S-G1-2", txt: "Volume of prisms/cylinders/spheres"}, {id: "S-G1-3", txt: "Surface area"}] },
        { id: "SAT_G2", ten: "Lines, angles, and triangles", dang: [{id: "S-G2-1", txt: "Parallel lines & Transversals"}, {id: "S-G2-2", txt: "Congruence & Similarity"}, {id: "S-G2-3", txt: "Triangle theorems"}] },
        { id: "SAT_G3", ten: "Right triangles and trigonometry", dang: [{id: "S-G3-1", txt: "Pythagorean theorem"}, {id: "S-G3-2", txt: "SOH CAH TOA"}, {id: "S-G3-3", txt: "Special right triangles"}] },
        { id: "SAT_G4", ten: "Circles", dang: [{id: "S-G4-1", txt: "Circle equations (h,k)"}, {id: "S-G4-2", txt: "Arc length & Sector area"}, {id: "S-G4-3", txt: "Angles in circles"}] }
    ]
};